"use strict";
exports.__esModule = true;
exports.ERROR_DEFAULT_MSG = exports.DATE_FORMAT = exports.URL_SEPERATOR = exports.JMETER_REPORT_INDEX_FILE_NAME = exports.JMETER_LOG_FILE_NAME = exports.LOG_JTL_FILE_NAME = exports.AZURE_STORAGE_ACCOUNT_NAME_PLACEHOLDER = exports.AZURE_STORAGE_ACCOUNT_URI = exports.DEFAULT_JMETER_LOG_DIR_NAME = exports.DEFAULT_JMETER_REPORT_DIR_NAME = exports.JMETER_BIN_Folder_NAME = exports.JMETER_FILE_NAME = exports.InputVariableType = exports.InputVariables = void 0;
var InputVariables;
(function (InputVariables) {
    InputVariables["JMX_SOURCE"] = "jmxSource";
    InputVariables["JMX_SOURCE_RUN_FILE_SOURCE_PATH"] = "jmxsourceRunFilePath";
    InputVariables["JMX_SOURCE_RUN_FILE_URL"] = "jmxsourceRunFileURL";
    InputVariables["JMX_PROPERTY_FILE_SOURCE"] = "jmxPropertySource";
    InputVariables["JMX_PROPERTY_FILE_SOURCE_PATH"] = "jmxPropertySourcePath";
    InputVariables["JMX_PROPERTY_FILE_URL"] = "jmxPropertySourceURL";
    InputVariables["JMX_INPUT_FILE_SOURCE"] = "jmxInputFilesSource";
    InputVariables["JMX_INPUT_FOLDER_SOURCE_PATH"] = "jmxInputFolderSourcePath";
    InputVariables["JMX_INPUT_FILES_URL"] = "jmxInputFilesUrls";
    InputVariables["JMX_BINARY_URI"] = "jmeterURI";
    InputVariables["JMETER_FOLDER_NAME"] = "jmeterFolderName";
    InputVariables["JMETER_LOG_FOLDER"] = "jmeterLogFolder";
    InputVariables["JMETER_REPORT_FOLDER"] = "jmeterReportFolder";
    InputVariables["COPY_RESULT_TO_AZURE_BLOB_STORAGE"] = "copyResultToAzureBlobStorage";
    InputVariables["PUBLISH_RESULTS_TO_BUILD_ARTIFACT"] = "publishResultsToBuildArtifact";
    InputVariables["TOKEN_REGEX"] = "tokenRegex";
    InputVariables["CONNECTED_SERVICE_ARM_NAME"] = "ConnectedServiceNameARM";
    InputVariables["STORAGE_ACCOUNT_RM"] = "StorageAccountRM";
    InputVariables["CONTAINER_NAME"] = "ContainerName";
    InputVariables["BLOB_PREFIX"] = "BlobPrefix";
    InputVariables["OUTPUT_STORAGE_URI"] = "outputStorageUri";
    InputVariables["ARTIFACT_NAME_REPORT"] = "artifactNameReport";
    InputVariables["ARTIFACT_NAME_LOG"] = "artifactNameLog";
})(InputVariables = exports.InputVariables || (exports.InputVariables = {}));
var InputVariableType;
(function (InputVariableType) {
    InputVariableType["SourceCode"] = "sourceCode";
    InputVariableType["Url"] = "url";
    InputVariableType["Urls"] = "urls";
    InputVariableType["None"] = "none";
})(InputVariableType = exports.InputVariableType || (exports.InputVariableType = {}));
exports.JMETER_FILE_NAME = 'apache-jmeter.tgz';
exports.JMETER_BIN_Folder_NAME = 'bin';
exports.DEFAULT_JMETER_REPORT_DIR_NAME = 'CurrentReport';
exports.DEFAULT_JMETER_LOG_DIR_NAME = 'CurrentLog';
exports.AZURE_STORAGE_ACCOUNT_URI = 'https://${storageAccountName}.blob.core.windows.net';
exports.AZURE_STORAGE_ACCOUNT_NAME_PLACEHOLDER = '${storageAccountName}';
exports.LOG_JTL_FILE_NAME = 'log.jtl';
exports.JMETER_LOG_FILE_NAME = 'jmeter.log';
exports.JMETER_REPORT_INDEX_FILE_NAME = 'index.html';
exports.URL_SEPERATOR = '/';
exports.DATE_FORMAT = 'DD-MMM-YYYY HH:mm:ss:SSS ZZ';
exports.ERROR_DEFAULT_MSG = 'Please note this extension is in beta version. We will be fixing the issues as reported and hence it is important for us to be able to analyze logs and fix the issue. If you encounter any issue please email at prateek.mishra@microsoft.com';
